/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IPhPlus: typeof import('~icons/ph/plus')['default']
    LoadingSpinner: typeof import('./../components/state/LoadingSpinner.vue')['default']
  }
}
